create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  category text,
  phone text,
  balance numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text,
  phone text,
  email text,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  client text,
  location text,
  status text not null default 'active' check (status in ('active','completed','paused')),
  budget numeric(12,2),
  start_date date,
  end_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.project_buildings (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  supplier_id bigint references public.suppliers(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null,
  building_id bigint references public.project_buildings(id) on delete set null,
  unit text,
  unit_price numeric(12,2),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  number text not null unique,
  supplier_id bigint references public.suppliers(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null,
  building_id bigint references public.project_buildings(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  total_amount numeric(12,2) not null default 0,
  paid_amount numeric(12,2) not null default 0,
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  status text not null default 'unpaid' check (status in ('unpaid','partial','paid')),
  invoice_date date,
  due_date date,
  notes text,
  image_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.worker_transactions (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references public.workers(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  type text not null check (type in ('credit','debit')),
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  description text,
  date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.project_memberships (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (project_id, user_id)
);

create table if not exists public.income_transactions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  description text,
  date date not null default current_date,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_projects_status on public.projects(status);
create index if not exists idx_project_buildings_project_id on public.project_buildings(project_id);
create index if not exists idx_products_project_id on public.products(project_id);
create index if not exists idx_products_building_id on public.products(building_id);
create index if not exists idx_invoices_project_id on public.invoices(project_id);
create index if not exists idx_invoices_building_id on public.invoices(building_id);
create index if not exists idx_invoices_product_id on public.invoices(product_id);
create index if not exists idx_invoices_supplier_id on public.invoices(supplier_id);
create index if not exists idx_worker_transactions_worker_id on public.worker_transactions(worker_id);
create index if not exists idx_worker_transactions_project_id on public.worker_transactions(project_id);
create index if not exists idx_project_memberships_project_id on public.project_memberships(project_id);
create index if not exists idx_project_memberships_user_id on public.project_memberships(user_id);
create index if not exists idx_income_transactions_project_id on public.income_transactions(project_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do update
  set email = excluded.email;
  return new;
end;
$$;

create or replace function public.sync_worker_balance()
returns trigger
language plpgsql
as $$
declare
  target_worker_id bigint;
begin
  target_worker_id := coalesce(new.worker_id, old.worker_id);

  update public.workers
  set balance = coalesce((
    select sum(case when wt.type = 'credit' then wt.amount else -wt.amount end)
    from public.worker_transactions wt
    where wt.worker_id = target_worker_id
  ), 0)
  where id = target_worker_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_sync_worker_balance on public.worker_transactions;
create trigger trg_sync_worker_balance
after insert or update or delete on public.worker_transactions
for each row execute function public.sync_worker_balance();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into storage.buckets (id, name, public)
values ('invoice-images', 'invoice-images', true)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.workers enable row level security;
alter table public.suppliers enable row level security;
alter table public.projects enable row level security;
alter table public.project_buildings enable row level security;
alter table public.products enable row level security;
alter table public.invoices enable row level security;
alter table public.worker_transactions enable row level security;
alter table public.project_memberships enable row level security;
alter table public.income_transactions enable row level security;

drop policy if exists "public read profiles" on public.profiles;
create policy "public read profiles" on public.profiles for select using (true);
drop policy if exists "public write profiles" on public.profiles;
create policy "public write profiles" on public.profiles for all using (true) with check (true);

drop policy if exists "public read workers" on public.workers;
create policy "public read workers" on public.workers for select using (true);
drop policy if exists "public write workers" on public.workers;
create policy "public write workers" on public.workers for all using (true) with check (true);

drop policy if exists "public read suppliers" on public.suppliers;
create policy "public read suppliers" on public.suppliers for select using (true);
drop policy if exists "public write suppliers" on public.suppliers;
create policy "public write suppliers" on public.suppliers for all using (true) with check (true);

drop policy if exists "public read projects" on public.projects;
create policy "public read projects" on public.projects for select using (true);
drop policy if exists "public write projects" on public.projects;
create policy "public write projects" on public.projects for all using (true) with check (true);

drop policy if exists "public read project buildings" on public.project_buildings;
create policy "public read project buildings" on public.project_buildings for select using (true);
drop policy if exists "public write project buildings" on public.project_buildings;
create policy "public write project buildings" on public.project_buildings for all using (true) with check (true);

drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select using (true);
drop policy if exists "public write products" on public.products;
create policy "public write products" on public.products for all using (true) with check (true);

drop policy if exists "public read invoices" on public.invoices;
create policy "public read invoices" on public.invoices for select using (true);
drop policy if exists "public write invoices" on public.invoices;
create policy "public write invoices" on public.invoices for all using (true) with check (true);

drop policy if exists "public read worker tx" on public.worker_transactions;
create policy "public read worker tx" on public.worker_transactions for select using (true);
drop policy if exists "public write worker tx" on public.worker_transactions;
create policy "public write worker tx" on public.worker_transactions for all using (true) with check (true);

drop policy if exists "public read project memberships" on public.project_memberships;
create policy "public read project memberships" on public.project_memberships for select using (true);
drop policy if exists "public write project memberships" on public.project_memberships;
create policy "public write project memberships" on public.project_memberships for all using (true) with check (true);

drop policy if exists "public read income tx" on public.income_transactions;
create policy "public read income tx" on public.income_transactions for select using (true);
drop policy if exists "public write income tx" on public.income_transactions;
create policy "public write income tx" on public.income_transactions for all using (true) with check (true);

drop policy if exists "public read invoice images" on storage.objects;
create policy "public read invoice images"
on storage.objects
for select
using (bucket_id = 'invoice-images');

drop policy if exists "public upload invoice images" on storage.objects;
create policy "public upload invoice images"
on storage.objects
for insert
with check (bucket_id = 'invoice-images');

drop policy if exists "public update invoice images" on storage.objects;
create policy "public update invoice images"
on storage.objects
for update
using (bucket_id = 'invoice-images')
with check (bucket_id = 'invoice-images');

drop policy if exists "public delete invoice images" on storage.objects;
create policy "public delete invoice images"
on storage.objects
for delete
using (bucket_id = 'invoice-images');
