create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  id text primary key default 'default' check (id = 'default'),
  company_logo_path text,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  category text,
  phone text,
  balance numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text,
  phone text,
  email text,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  client text,
  location text,
  status text not null default 'active' check (status in ('active', 'completed', 'paused')),
  budget numeric(12,2) check (budget is null or budget >= 0),
  start_date date,
  end_date date,
  created_at timestamptz not null default now(),
  constraint projects_dates_check check (end_date is null or start_date is null or end_date >= start_date)
);

create table if not exists public.project_buildings (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  supplier_id bigint references public.suppliers(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null,
  building_id bigint references public.project_buildings(id) on delete set null,
  unit text,
  unit_price numeric(12,2) check (unit_price is null or unit_price >= 0),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  number text not null unique,
  supplier_id bigint references public.suppliers(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null,
  building_id bigint references public.project_buildings(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  paid_amount numeric(12,2) not null default 0 check (paid_amount >= 0 and paid_amount <= total_amount),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  status text not null default 'unpaid' check (status in ('unpaid', 'partial', 'paid')),
  invoice_date date,
  due_date date,
  notes text,
  image_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint invoices_dates_check check (due_date is null or invoice_date is null or due_date >= invoice_date)
);

create table if not exists public.worker_transactions (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references public.workers(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  type text not null check (type in ('credit', 'debit')),
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  description text,
  date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.project_memberships (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (project_id, user_id)
);

create table if not exists public.income_transactions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  description text,
  date date not null default current_date,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_projects_status on public.projects(status);
create index if not exists idx_projects_start_date on public.projects(start_date);
create index if not exists idx_projects_end_date on public.projects(end_date);
create index if not exists idx_project_buildings_project_id on public.project_buildings(project_id);
create index if not exists idx_products_project_id on public.products(project_id);
create index if not exists idx_products_supplier_id on public.products(supplier_id);
create index if not exists idx_products_building_id on public.products(building_id);
create index if not exists idx_invoices_project_id on public.invoices(project_id);
create index if not exists idx_invoices_building_id on public.invoices(building_id);
create index if not exists idx_invoices_product_id on public.invoices(product_id);
create index if not exists idx_invoices_supplier_id on public.invoices(supplier_id);
create index if not exists idx_invoices_status on public.invoices(status);
create index if not exists idx_invoices_invoice_date on public.invoices(invoice_date);
create index if not exists idx_invoices_due_date on public.invoices(due_date);
create index if not exists idx_worker_transactions_worker_id on public.worker_transactions(worker_id);
create index if not exists idx_worker_transactions_project_id on public.worker_transactions(project_id);
create index if not exists idx_worker_transactions_date on public.worker_transactions(date);
create index if not exists idx_project_memberships_project_id on public.project_memberships(project_id);
create index if not exists idx_project_memberships_user_id on public.project_memberships(user_id);
create index if not exists idx_income_transactions_project_id on public.income_transactions(project_id);
create index if not exists idx_income_transactions_date on public.income_transactions(date);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  assigned_role text := 'user';
begin
  if not exists (select 1 from public.profiles) then
    assigned_role := 'admin';
  end if;

  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''), assigned_role)
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name);

  return new;
end;
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select p.role
      from public.profiles as p
      where p.id = auth.uid()
    ),
    'user'
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.role() = 'authenticated' and public.current_user_role() = 'admin';
$$;

create or replace function public.can_access_project(target_project_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    auth.role() = 'authenticated'
    and (
      target_project_id is null
      or public.is_admin()
      or exists (
        select 1
        from public.project_memberships as pm
        where pm.project_id = target_project_id
          and pm.user_id = auth.uid()
      )
    );
$$;

create or replace function public.can_access_invoice_object(object_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  object_prefix text;
  project_id_text text;
begin
  if auth.role() <> 'authenticated' then
    return false;
  end if;

  object_prefix := split_part(coalesce(object_name, ''), '/', 1);

  if object_prefix = 'shared' then
    return true;
  end if;

  if object_prefix ~ '^[0-9]{4}$' then
    return true;
  end if;

  if object_prefix like 'project-%' then
    project_id_text := nullif(replace(object_prefix, 'project-', ''), '');
    return public.can_access_project(project_id_text::bigint);
  end if;

  return false;
exception
  when others then
    return false;
end;
$$;

create or replace function public.sync_worker_balance()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  target_worker_id bigint;
begin
  target_worker_id := coalesce(new.worker_id, old.worker_id);

  update public.workers
  set balance = coalesce(
    (
      select sum(case when wt.type = 'credit' then wt.amount else -wt.amount end)
      from public.worker_transactions as wt
      where wt.worker_id = target_worker_id
    ),
    0
  )
  where id = target_worker_id;

  return coalesce(new, old);
end;
$$;

create or replace function public.replace_project_buildings(
  p_project_id bigint,
  p_building_names text[]
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  cleaned_names text[];
begin
  if not public.is_admin() then
    raise exception 'Only administrators can update project buildings.';
  end if;

  cleaned_names := array(
    select distinct trimmed_name
    from (
      select nullif(btrim(name), '') as trimmed_name
      from unnest(coalesce(p_building_names, array[]::text[])) as name
    ) as prepared_names
    where trimmed_name is not null
    order by trimmed_name
  );

  delete from public.project_buildings
  where project_id = p_project_id;

  if coalesce(array_length(cleaned_names, 1), 0) = 0 then
    return;
  end if;

  insert into public.project_buildings (project_id, name)
  select p_project_id, name
  from unnest(cleaned_names) as name;
end;
$$;

create or replace function public.save_project_with_buildings(
  p_id bigint,
  p_name text,
  p_client text,
  p_location text,
  p_status text,
  p_budget numeric,
  p_start_date date,
  p_end_date date,
  p_building_names text[]
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  target_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Only administrators can create or update projects.';
  end if;

  if nullif(btrim(p_name), '') is null then
    raise exception 'Project name is required.';
  end if;

  if p_budget is not null and p_budget < 0 then
    raise exception 'Project budget cannot be negative.';
  end if;

  if p_end_date is not null and p_start_date is not null and p_end_date < p_start_date then
    raise exception 'Project end date cannot be earlier than the start date.';
  end if;

  if p_id is null then
    insert into public.projects (
      name,
      client,
      location,
      status,
      budget,
      start_date,
      end_date
    )
    values (
      btrim(p_name),
      nullif(btrim(p_client), ''),
      nullif(btrim(p_location), ''),
      coalesce(nullif(btrim(p_status), ''), 'active'),
      p_budget,
      p_start_date,
      p_end_date
    )
    returning id into target_id;
  else
    update public.projects
    set
      name = btrim(p_name),
      client = nullif(btrim(p_client), ''),
      location = nullif(btrim(p_location), ''),
      status = coalesce(nullif(btrim(p_status), ''), 'active'),
      budget = p_budget,
      start_date = p_start_date,
      end_date = p_end_date
    where id = p_id
    returning id into target_id;

    if target_id is null then
      raise exception 'Project not found.';
    end if;
  end if;

  perform public.replace_project_buildings(target_id, p_building_names);

  return target_id;
end;
$$;

create or replace function public.replace_user_project_memberships(
  p_user_id uuid,
  p_project_ids bigint[]
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only administrators can update project memberships.';
  end if;

  delete from public.project_memberships
  where user_id = p_user_id;

  if coalesce(array_length(p_project_ids, 1), 0) = 0 then
    return;
  end if;

  insert into public.project_memberships (user_id, project_id)
  select p_user_id, distinct_project_id
  from (
    select distinct project_id as distinct_project_id
    from unnest(p_project_ids) as project_id
  ) as distinct_projects
  where exists (
    select 1
    from public.projects as p
    where p.id = distinct_projects.distinct_project_id
  );
end;
$$;

create or replace view public.app_projects
with (security_invoker = true)
as
select
  p.id,
  p.name,
  p.client,
  p.location,
  p.status,
  p.budget,
  p.start_date,
  p.end_date,
  p.created_at,
  count(pb.id)::int as building_count
from public.projects as p
left join public.project_buildings as pb
  on pb.project_id = p.id
group by
  p.id,
  p.name,
  p.client,
  p.location,
  p.status,
  p.budget,
  p.start_date,
  p.end_date,
  p.created_at;

create or replace view public.app_products
with (security_invoker = true)
as
select
  pr.id,
  pr.name,
  pr.supplier_id,
  s.name as supplier_name,
  pr.project_id,
  p.name as project_name,
  pr.building_id,
  pb.name as building_name,
  pr.unit,
  pr.unit_price,
  pr.currency,
  pr.created_at
from public.products as pr
left join public.suppliers as s
  on s.id = pr.supplier_id
left join public.projects as p
  on p.id = pr.project_id
left join public.project_buildings as pb
  on pb.id = pr.building_id;

create or replace view public.app_worker_transactions
with (security_invoker = true)
as
select
  wt.id,
  wt.worker_id,
  wt.project_id,
  p.name as project_name,
  wt.type,
  wt.amount,
  wt.currency,
  wt.description,
  wt.date,
  wt.created_at
from public.worker_transactions as wt
left join public.projects as p
  on p.id = wt.project_id;

create or replace view public.app_income_transactions
with (security_invoker = true)
as
select
  it.id,
  it.project_id,
  p.name as project_name,
  it.amount,
  it.currency,
  it.description,
  it.date,
  it.created_by,
  coalesce(created_profile.full_name, created_profile.email) as created_by_name,
  it.created_at
from public.income_transactions as it
left join public.projects as p
  on p.id = it.project_id
left join public.profiles as created_profile
  on created_profile.id = it.created_by;

create or replace view public.app_invoices
with (security_invoker = true)
as
select
  i.id,
  i.number,
  i.status,
  i.supplier_id,
  s.name as supplier_name,
  i.project_id,
  p.name as project_name,
  i.building_id,
  pb.name as building_name,
  i.product_id,
  pr.name as product_name,
  i.total_amount,
  i.paid_amount,
  greatest(i.total_amount - i.paid_amount, 0) as remaining_amount,
  i.currency,
  i.invoice_date,
  i.due_date,
  i.notes,
  i.image_url,
  i.created_by,
  coalesce(created_profile.full_name, created_profile.email) as created_by_name,
  i.created_at
from public.invoices as i
left join public.suppliers as s
  on s.id = i.supplier_id
left join public.projects as p
  on p.id = i.project_id
left join public.project_buildings as pb
  on pb.id = i.building_id
left join public.products as pr
  on pr.id = i.product_id
left join public.profiles as created_profile
  on created_profile.id = i.created_by;

create or replace function public.get_dashboard_overview()
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
with visible_projects as (
  select id, name, status
  from public.projects
),
visible_invoices as (
  select
    id,
    number,
    status,
    supplier_name,
    project_name,
    project_id,
    total_amount,
    paid_amount,
    remaining_amount
  from public.app_invoices
),
visible_workers as (
  select id, name, role, balance
  from public.workers
),
visible_transactions as (
  select worker_id, type, amount
  from public.worker_transactions
),
project_summaries as (
  select
    p.id,
    p.name,
    p.status,
    count(i.id)::int as invoice_count,
    coalesce(sum(i.total_amount), 0)::numeric(12,2) as total_invoiced,
    coalesce(sum(i.paid_amount), 0)::numeric(12,2) as total_paid,
    coalesce(sum(i.remaining_amount), 0)::numeric(12,2) as remaining
  from visible_projects as p
  left join visible_invoices as i
    on i.project_id = p.id
  group by p.id, p.name, p.status
),
worker_summaries as (
  select
    w.id,
    w.name,
    w.role,
    w.balance,
    coalesce(sum(case when wt.type = 'credit' then wt.amount else 0 end), 0)::numeric(12,2) as total_credit,
    coalesce(sum(case when wt.type = 'debit' then wt.amount else 0 end), 0)::numeric(12,2) as total_debit
  from visible_workers as w
  left join visible_transactions as wt
    on wt.worker_id = w.id
  group by w.id, w.name, w.role, w.balance
),
invoice_summaries as (
  select
    id,
    number,
    status,
    supplier_name,
    project_name,
    total_amount,
    paid_amount,
    remaining_amount as remaining
  from visible_invoices
)
select jsonb_build_object(
  'totalWorkers',
  (select count(*) from visible_workers),
  'activeProjects',
  (select count(*) from visible_projects where status = 'active'),
  'totalSuppliers',
  (select count(*) from public.suppliers),
  'invoicesUnpaid',
  (select count(*) from visible_invoices where status <> 'paid'),
  'totalInvoiceAmount',
  (select coalesce(sum(total_amount), 0) from visible_invoices),
  'totalPaidAmount',
  (select coalesce(sum(paid_amount), 0) from visible_invoices),
  'remainingAmount',
  (select coalesce(sum(remaining_amount), 0) from visible_invoices),
  'projectsSummary',
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', ps.id,
          'name', ps.name,
          'status', ps.status,
          'invoiceCount', ps.invoice_count,
          'totalInvoiced', ps.total_invoiced,
          'totalPaid', ps.total_paid,
          'remaining', ps.remaining
        )
        order by ps.remaining desc, ps.name asc
      )
      from project_summaries as ps
    ),
    '[]'::jsonb
  ),
  'workersSummary',
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', ws.id,
          'name', ws.name,
          'role', ws.role,
          'balance', ws.balance,
          'totalCredit', ws.total_credit,
          'totalDebit', ws.total_debit
        )
        order by abs(ws.balance) desc, ws.name asc
      )
      from worker_summaries as ws
    ),
    '[]'::jsonb
  ),
  'invoicesSummary',
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', inv.id,
          'number', inv.number,
          'status', inv.status,
          'supplierName', inv.supplier_name,
          'projectName', inv.project_name,
          'totalAmount', inv.total_amount,
          'paidAmount', inv.paid_amount,
          'remaining', inv.remaining
        )
        order by inv.remaining desc, inv.number asc
      )
      from invoice_summaries as inv
    ),
    '[]'::jsonb
  )
);
$$;

drop trigger if exists trg_sync_worker_balance on public.worker_transactions;
create trigger trg_sync_worker_balance
after insert or update or delete on public.worker_transactions
for each row execute function public.sync_worker_balance();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, full_name, role)
select
  users.id,
  users.email,
  coalesce(users.raw_user_meta_data->>'full_name', ''),
  case
    when row_number() over (order by users.created_at asc, users.id asc) = 1 then 'admin'
    else 'user'
  end
from auth.users as users
on conflict (id) do update
set
  email = excluded.email,
  full_name = coalesce(excluded.full_name, public.profiles.full_name),
  role = case when public.profiles.role = 'admin' then 'admin' else excluded.role end;

insert into storage.buckets (id, name, public)
values ('invoice-images', 'invoice-images', false)
on conflict (id) do update
set public = false;

insert into storage.buckets (id, name, public)
values ('branding-assets', 'branding-assets', true)
on conflict (id) do update
set public = true;

insert into public.app_settings (id)
values ('default')
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.app_settings enable row level security;
alter table public.workers enable row level security;
alter table public.suppliers enable row level security;
alter table public.projects enable row level security;
alter table public.project_buildings enable row level security;
alter table public.products enable row level security;
alter table public.invoices enable row level security;
alter table public.worker_transactions enable row level security;
alter table public.project_memberships enable row level security;
alter table public.income_transactions enable row level security;

drop policy if exists "profiles authenticated read" on public.profiles;
drop policy if exists "profiles read own or admin" on public.profiles;
create policy "profiles authenticated read"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "profiles insert self" on public.profiles;
create policy "profiles insert self"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "app settings public read" on public.app_settings;
create policy "app settings public read"
on public.app_settings
for select
to anon, authenticated
using (true);

drop policy if exists "app settings admin write" on public.app_settings;
create policy "app settings admin write"
on public.app_settings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "profiles update own or admin" on public.profiles;
create policy "profiles update own or admin"
on public.profiles
for update
to authenticated
using (auth.uid() = id or public.is_admin())
with check (
  public.is_admin()
  or (
    auth.uid() = id
    and role = public.current_user_role()
  )
);

drop policy if exists "workers authenticated access" on public.workers;
create policy "workers authenticated access"
on public.workers
for all
to authenticated
using (true)
with check (true);

drop policy if exists "suppliers authenticated access" on public.suppliers;
create policy "suppliers authenticated access"
on public.suppliers
for all
to authenticated
using (true)
with check (true);

drop policy if exists "projects readable by membership" on public.projects;
create policy "projects readable by membership"
on public.projects
for select
to authenticated
using (public.can_access_project(id));

drop policy if exists "projects admin write" on public.projects;
create policy "projects admin write"
on public.projects
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "project buildings readable by membership" on public.project_buildings;
create policy "project buildings readable by membership"
on public.project_buildings
for select
to authenticated
using (public.can_access_project(project_id));

drop policy if exists "project buildings admin write" on public.project_buildings;
create policy "project buildings admin write"
on public.project_buildings
for all
to authenticated
using (public.is_admin() and public.can_access_project(project_id))
with check (public.is_admin() and public.can_access_project(project_id));

drop policy if exists "products scoped access" on public.products;
create policy "products scoped access"
on public.products
for all
to authenticated
using (public.can_access_project(project_id))
with check (public.can_access_project(project_id));

drop policy if exists "invoices scoped access" on public.invoices;
create policy "invoices scoped access"
on public.invoices
for all
to authenticated
using (public.can_access_project(project_id))
with check (public.can_access_project(project_id));

drop policy if exists "worker transactions authenticated read" on public.worker_transactions;
create policy "worker transactions authenticated read"
on public.worker_transactions
for select
to authenticated
using (true);

drop policy if exists "worker transactions authenticated write" on public.worker_transactions;
create policy "worker transactions authenticated write"
on public.worker_transactions
for insert
to authenticated
with check (public.can_access_project(project_id));

drop policy if exists "worker transactions authenticated update" on public.worker_transactions;
create policy "worker transactions authenticated update"
on public.worker_transactions
for update
to authenticated
using (true)
with check (public.can_access_project(project_id));

drop policy if exists "worker transactions authenticated delete" on public.worker_transactions;
create policy "worker transactions authenticated delete"
on public.worker_transactions
for delete
to authenticated
using (true);

drop policy if exists "project memberships admin access" on public.project_memberships;
create policy "project memberships admin access"
on public.project_memberships
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "income transactions scoped access" on public.income_transactions;
create policy "income transactions scoped access"
on public.income_transactions
for all
to authenticated
using (public.can_access_project(project_id))
with check (public.can_access_project(project_id));

drop policy if exists "invoice images authenticated read" on storage.objects;
create policy "invoice images authenticated read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'invoice-images'
  and public.can_access_invoice_object(name)
);

drop policy if exists "invoice images authenticated insert" on storage.objects;
create policy "invoice images authenticated insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'invoice-images'
  and public.can_access_invoice_object(name)
);

drop policy if exists "invoice images authenticated update" on storage.objects;
create policy "invoice images authenticated update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'invoice-images'
  and public.can_access_invoice_object(name)
)
with check (
  bucket_id = 'invoice-images'
  and public.can_access_invoice_object(name)
);

drop policy if exists "invoice images authenticated delete" on storage.objects;
create policy "invoice images authenticated delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'invoice-images'
  and public.can_access_invoice_object(name)
);

drop policy if exists "branding assets admin insert" on storage.objects;
create policy "branding assets admin insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'branding-assets'
  and public.is_admin()
);

drop policy if exists "branding assets admin update" on storage.objects;
create policy "branding assets admin update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'branding-assets'
  and public.is_admin()
)
with check (
  bucket_id = 'branding-assets'
  and public.is_admin()
);

drop policy if exists "branding assets admin delete" on storage.objects;
create policy "branding assets admin delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'branding-assets'
  and public.is_admin()
);

grant usage on schema public to anon;
grant select on public.app_settings to anon;
grant usage on schema public to authenticated;
grant select on public.app_settings to authenticated;
grant select on public.app_projects to authenticated;
grant select on public.app_products to authenticated;
grant select on public.app_worker_transactions to authenticated;
grant select on public.app_income_transactions to authenticated;
grant select on public.app_invoices to authenticated;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.can_access_project(bigint) to authenticated;
grant execute on function public.can_access_invoice_object(text) to authenticated;
grant execute on function public.replace_project_buildings(bigint, text[]) to authenticated;
grant execute on function public.save_project_with_buildings(bigint, text, text, text, text, numeric, date, date, text[]) to authenticated;
grant execute on function public.replace_user_project_memberships(uuid, bigint[]) to authenticated;
grant execute on function public.get_dashboard_overview() to authenticated;

create table if not exists public.invoice_history (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  change_type text not null check (change_type in ('created', 'updated')),
  number text not null,
  supplier_id bigint references public.suppliers(id) on delete set null,
  supplier_name text,
  project_id bigint references public.projects(id) on delete set null,
  project_name text,
  building_id bigint references public.project_buildings(id) on delete set null,
  building_name text,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  paid_amount numeric(12,2) not null default 0 check (paid_amount >= 0 and paid_amount <= total_amount),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  status text not null default 'unpaid' check (status in ('unpaid', 'partial', 'paid')),
  invoice_date date,
  due_date date,
  notes text,
  image_url text,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_by_name text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_invoice_history_invoice_id on public.invoice_history(invoice_id);
create index if not exists idx_invoice_history_changed_at on public.invoice_history(changed_at);

create or replace function public.log_invoice_history()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  actor_id uuid;
  actor_name text;
  snapshot_supplier_name text;
  snapshot_project_name text;
  snapshot_building_name text;
  snapshot_product_name text;
begin
  if tg_op = 'UPDATE' and new is not distinct from old then
    return new;
  end if;

  if tg_op = 'INSERT' then
    actor_id := coalesce(auth.uid(), new.created_by);
  else
    actor_id := coalesce(auth.uid(), new.created_by, old.created_by);
  end if;

  if actor_id is not null then
    select coalesce(p.full_name, p.email)
    into actor_name
    from public.profiles as p
    where p.id = actor_id;
  end if;

  if new.supplier_id is not null then
    select s.name
    into snapshot_supplier_name
    from public.suppliers as s
    where s.id = new.supplier_id;
  end if;

  if new.project_id is not null then
    select p.name
    into snapshot_project_name
    from public.projects as p
    where p.id = new.project_id;
  end if;

  if new.building_id is not null then
    select pb.name
    into snapshot_building_name
    from public.project_buildings as pb
    where pb.id = new.building_id;
  end if;

  if new.product_id is not null then
    select pr.name
    into snapshot_product_name
    from public.products as pr
    where pr.id = new.product_id;
  end if;

  insert into public.invoice_history (
    invoice_id,
    change_type,
    number,
    supplier_id,
    supplier_name,
    project_id,
    project_name,
    building_id,
    building_name,
    product_id,
    product_name,
    total_amount,
    paid_amount,
    currency,
    status,
    invoice_date,
    due_date,
    notes,
    image_url,
    changed_by,
    changed_by_name,
    changed_at
  )
  values (
    new.id,
    case when tg_op = 'INSERT' then 'created' else 'updated' end,
    new.number,
    new.supplier_id,
    snapshot_supplier_name,
    new.project_id,
    snapshot_project_name,
    new.building_id,
    snapshot_building_name,
    new.product_id,
    snapshot_product_name,
    new.total_amount,
    new.paid_amount,
    new.currency,
    new.status,
    new.invoice_date,
    new.due_date,
    new.notes,
    new.image_url,
    actor_id,
    actor_name,
    case when tg_op = 'INSERT' then coalesce(new.created_at, now()) else now() end
  );

  return new;
end;
$$;

drop trigger if exists trg_log_invoice_history on public.invoices;
create trigger trg_log_invoice_history
after insert or update on public.invoices
for each row execute function public.log_invoice_history();

insert into public.invoice_history (
  invoice_id,
  change_type,
  number,
  supplier_id,
  supplier_name,
  project_id,
  project_name,
  building_id,
  building_name,
  product_id,
  product_name,
  total_amount,
  paid_amount,
  currency,
  status,
  invoice_date,
  due_date,
  notes,
  image_url,
  changed_by,
  changed_by_name,
  changed_at
)
select
  i.id,
  'created',
  i.number,
  i.supplier_id,
  s.name,
  i.project_id,
  p.name,
  i.building_id,
  pb.name,
  i.product_id,
  pr.name,
  i.total_amount,
  i.paid_amount,
  i.currency,
  i.status,
  i.invoice_date,
  i.due_date,
  i.notes,
  i.image_url,
  i.created_by,
  coalesce(created_profile.full_name, created_profile.email),
  coalesce(i.created_at, now())
from public.invoices as i
left join public.suppliers as s
  on s.id = i.supplier_id
left join public.projects as p
  on p.id = i.project_id
left join public.project_buildings as pb
  on pb.id = i.building_id
left join public.products as pr
  on pr.id = i.product_id
left join public.profiles as created_profile
  on created_profile.id = i.created_by
where not exists (
  select 1
  from public.invoice_history as ih
  where ih.invoice_id = i.id
);

create or replace view public.app_invoice_history
with (security_invoker = true)
as
select
  ih.id,
  ih.invoice_id,
  ih.change_type,
  ih.number,
  ih.status,
  ih.supplier_id,
  ih.supplier_name,
  ih.project_id,
  ih.project_name,
  ih.building_id,
  ih.building_name,
  ih.product_id,
  ih.product_name,
  ih.total_amount,
  ih.paid_amount,
  greatest(ih.total_amount - ih.paid_amount, 0) as remaining_amount,
  ih.currency,
  ih.invoice_date,
  ih.due_date,
  ih.notes,
  ih.image_url,
  ih.changed_by,
  ih.changed_by_name,
  ih.changed_at
from public.invoice_history as ih;

alter table public.invoice_history enable row level security;

drop policy if exists "invoice history scoped read" on public.invoice_history;
create policy "invoice history scoped read"
on public.invoice_history
for select
to authenticated
using (public.can_access_project(project_id));

drop policy if exists "invoice history authenticated insert" on public.invoice_history;
create policy "invoice history authenticated insert"
on public.invoice_history
for insert
to authenticated
with check (public.can_access_project(project_id));

grant select on public.app_invoice_history to authenticated;
