create table if not exists public.party_transactions (
  id bigint generated by default as identity primary key,
  party_type text not null check (party_type in ('worker', 'supplier')),
  worker_id bigint references public.workers(id) on delete cascade,
  supplier_id bigint references public.suppliers(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  type text not null check (type in ('credit', 'debit')),
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  amount_usd numeric(12,2) not null default 0,
  amount_iqd numeric(12,2) not null default 0,
  description text,
  date date not null default current_date,
  source_invoice_id bigint references public.invoices(id) on delete cascade,
  source_kind text,
  created_at timestamptz not null default now(),
  constraint party_transactions_party_check check (
    (party_type = 'worker' and worker_id is not null and supplier_id is null)
    or (party_type = 'supplier' and supplier_id is not null and worker_id is null)
  ),
  constraint party_transactions_dual_currency_positive check (
    amount_usd >= 0
    and amount_iqd >= 0
    and (amount_usd > 0 or amount_iqd > 0)
  )
);

create index if not exists idx_party_transactions_party
  on public.party_transactions(party_type, worker_id, supplier_id);
create index if not exists idx_party_transactions_worker_id
  on public.party_transactions(worker_id);
create index if not exists idx_party_transactions_supplier_id
  on public.party_transactions(supplier_id);
create index if not exists idx_party_transactions_project_id
  on public.party_transactions(project_id);
create index if not exists idx_party_transactions_date
  on public.party_transactions(date);
create index if not exists idx_party_transactions_source_invoice_id
  on public.party_transactions(source_invoice_id);
create unique index if not exists idx_party_transactions_invoice_source
  on public.party_transactions(source_invoice_id, party_type, type)
  where source_kind in ('labor_expense', 'supplier_expense');

alter table public.party_transactions enable row level security;

drop policy if exists "party transactions scoped select" on public.party_transactions;
create policy "party transactions scoped select"
on public.party_transactions
for select
to authenticated
using (public.can_access_project(project_id));

drop policy if exists "party transactions scoped insert" on public.party_transactions;
create policy "party transactions scoped insert"
on public.party_transactions
for insert
to authenticated
with check (public.can_access_project(project_id));

drop policy if exists "party transactions scoped update" on public.party_transactions;
create policy "party transactions scoped update"
on public.party_transactions
for update
to authenticated
using (public.can_access_project(project_id))
with check (public.can_access_project(project_id));

drop policy if exists "party transactions scoped delete" on public.party_transactions;
create policy "party transactions scoped delete"
on public.party_transactions
for delete
to authenticated
using (public.can_access_project(project_id));

drop trigger if exists trg_sync_labor_invoice_worker_transactions on public.invoices;
drop trigger if exists trg_sync_worker_balance on public.worker_transactions;

insert into public.party_transactions (
  party_type,
  worker_id,
  project_id,
  type,
  amount,
  currency,
  amount_usd,
  amount_iqd,
  description,
  date,
  source_invoice_id,
  source_kind,
  created_at
)
select
  'worker',
  wt.worker_id,
  wt.project_id,
  wt.type,
  wt.amount,
  wt.currency,
  coalesce(wt.amount_usd, case when wt.currency = 'USD' then wt.amount else 0 end),
  coalesce(wt.amount_iqd, case when wt.currency = 'IQD' then wt.amount else 0 end),
  wt.description,
  wt.date,
  wt.source_invoice_id,
  case
    when wt.source_invoice_id is not null and wt.source_kind is null then 'labor_expense'
    else wt.source_kind
  end,
  wt.created_at
from public.worker_transactions as wt
on conflict (source_invoice_id, party_type, type)
where source_kind in ('labor_expense', 'supplier_expense')
do update set
  worker_id = excluded.worker_id,
  project_id = excluded.project_id,
  amount = excluded.amount,
  currency = excluded.currency,
  amount_usd = excluded.amount_usd,
  amount_iqd = excluded.amount_iqd,
  description = excluded.description,
  date = excluded.date,
  source_kind = excluded.source_kind;

insert into public.party_transactions (
  party_type,
  worker_id,
  project_id,
  type,
  amount,
  currency,
  amount_usd,
  amount_iqd,
  description,
  date,
  source_invoice_id,
  source_kind,
  created_at
)
select
  'worker',
  i.labor_worker_id,
  i.project_id,
  'credit',
  case when coalesce(i.total_amount_usd, 0) > 0 then coalesce(i.total_amount_usd, 0) else coalesce(i.total_amount_iqd, 0) end,
  case when coalesce(i.total_amount_usd, 0) > 0 then 'USD' else 'IQD' end,
  coalesce(i.total_amount_usd, 0),
  coalesce(i.total_amount_iqd, 0),
  'Labor earned: ' || coalesce(nullif(i.number, ''), 'Labor expense'),
  coalesce(i.invoice_date, current_date),
  i.id,
  'labor_expense',
  coalesce(i.created_at, now())
from public.invoices as i
where i.expense_type = 'labor'
  and i.record_status = 'active'
  and i.labor_worker_id is not null
  and (coalesce(i.total_amount_usd, 0) > 0 or coalesce(i.total_amount_iqd, 0) > 0)
on conflict (source_invoice_id, party_type, type)
where source_kind in ('labor_expense', 'supplier_expense')
do update set
  worker_id = excluded.worker_id,
  supplier_id = null,
  project_id = excluded.project_id,
  amount = excluded.amount,
  currency = excluded.currency,
  amount_usd = excluded.amount_usd,
  amount_iqd = excluded.amount_iqd,
  description = excluded.description,
  date = excluded.date,
  source_kind = excluded.source_kind;

insert into public.party_transactions (
  party_type,
  worker_id,
  project_id,
  type,
  amount,
  currency,
  amount_usd,
  amount_iqd,
  description,
  date,
  source_invoice_id,
  source_kind,
  created_at
)
select
  'worker',
  i.labor_worker_id,
  i.project_id,
  'debit',
  case when coalesce(i.paid_amount_usd, 0) > 0 then coalesce(i.paid_amount_usd, 0) else coalesce(i.paid_amount_iqd, 0) end,
  case when coalesce(i.paid_amount_usd, 0) > 0 then 'USD' else 'IQD' end,
  coalesce(i.paid_amount_usd, 0),
  coalesce(i.paid_amount_iqd, 0),
  'Labor paid: ' || coalesce(nullif(i.number, ''), 'Labor expense'),
  coalesce(i.invoice_date, current_date),
  i.id,
  'labor_expense',
  coalesce(i.created_at, now())
from public.invoices as i
where i.expense_type = 'labor'
  and i.record_status = 'active'
  and i.labor_worker_id is not null
  and (coalesce(i.paid_amount_usd, 0) > 0 or coalesce(i.paid_amount_iqd, 0) > 0)
on conflict (source_invoice_id, party_type, type)
where source_kind in ('labor_expense', 'supplier_expense')
do update set
  worker_id = excluded.worker_id,
  supplier_id = null,
  project_id = excluded.project_id,
  amount = excluded.amount,
  currency = excluded.currency,
  amount_usd = excluded.amount_usd,
  amount_iqd = excluded.amount_iqd,
  description = excluded.description,
  date = excluded.date,
  source_kind = excluded.source_kind;

insert into public.party_transactions (
  party_type,
  supplier_id,
  project_id,
  type,
  amount,
  currency,
  amount_usd,
  amount_iqd,
  description,
  date,
  source_invoice_id,
  source_kind,
  created_at
)
select
  'supplier',
  i.supplier_id,
  i.project_id,
  'credit',
  case when coalesce(i.total_amount_usd, 0) > 0 then coalesce(i.total_amount_usd, 0) else coalesce(i.total_amount_iqd, 0) end,
  case when coalesce(i.total_amount_usd, 0) > 0 then 'USD' else 'IQD' end,
  coalesce(i.total_amount_usd, 0),
  coalesce(i.total_amount_iqd, 0),
  'Supplier invoice: ' || coalesce(nullif(i.number, ''), 'Expense'),
  coalesce(i.invoice_date, current_date),
  i.id,
  'supplier_expense',
  coalesce(i.created_at, now())
from public.invoices as i
where i.expense_type = 'products'
  and i.record_status = 'active'
  and i.supplier_id is not null
  and (coalesce(i.total_amount_usd, 0) > 0 or coalesce(i.total_amount_iqd, 0) > 0)
on conflict (source_invoice_id, party_type, type)
where source_kind in ('labor_expense', 'supplier_expense')
do update set
  worker_id = null,
  supplier_id = excluded.supplier_id,
  project_id = excluded.project_id,
  amount = excluded.amount,
  currency = excluded.currency,
  amount_usd = excluded.amount_usd,
  amount_iqd = excluded.amount_iqd,
  description = excluded.description,
  date = excluded.date,
  source_kind = excluded.source_kind;

insert into public.party_transactions (
  party_type,
  supplier_id,
  project_id,
  type,
  amount,
  currency,
  amount_usd,
  amount_iqd,
  description,
  date,
  source_invoice_id,
  source_kind,
  created_at
)
select
  'supplier',
  i.supplier_id,
  i.project_id,
  'debit',
  case when coalesce(i.paid_amount_usd, 0) > 0 then coalesce(i.paid_amount_usd, 0) else coalesce(i.paid_amount_iqd, 0) end,
  case when coalesce(i.paid_amount_usd, 0) > 0 then 'USD' else 'IQD' end,
  coalesce(i.paid_amount_usd, 0),
  coalesce(i.paid_amount_iqd, 0),
  'Supplier paid: ' || coalesce(nullif(i.number, ''), 'Expense'),
  coalesce(i.invoice_date, current_date),
  i.id,
  'supplier_expense',
  coalesce(i.created_at, now())
from public.invoices as i
where i.expense_type = 'products'
  and i.record_status = 'active'
  and i.supplier_id is not null
  and (coalesce(i.paid_amount_usd, 0) > 0 or coalesce(i.paid_amount_iqd, 0) > 0)
on conflict (source_invoice_id, party_type, type)
where source_kind in ('labor_expense', 'supplier_expense')
do update set
  worker_id = null,
  supplier_id = excluded.supplier_id,
  project_id = excluded.project_id,
  amount = excluded.amount,
  currency = excluded.currency,
  amount_usd = excluded.amount_usd,
  amount_iqd = excluded.amount_iqd,
  description = excluded.description,
  date = excluded.date,
  source_kind = excluded.source_kind;

drop view if exists public.app_supplier_transactions;
drop view if exists public.app_party_transactions;
drop view if exists public.app_worker_transactions;

create or replace view public.app_party_transactions
with (security_invoker = true)
as
select
  pt.id,
  pt.party_type,
  coalesce(pt.worker_id, pt.supplier_id) as party_id,
  coalesce(w.name, s.name) as party_name,
  pt.worker_id,
  w.name as worker_name,
  pt.supplier_id,
  s.name as supplier_name,
  pt.project_id,
  p.name as project_name,
  pt.type,
  pt.amount,
  pt.currency,
  pt.description,
  pt.date,
  pt.created_at,
  pt.amount_usd,
  pt.amount_iqd,
  pt.source_invoice_id,
  pt.source_kind
from public.party_transactions as pt
left join public.workers as w
  on w.id = pt.worker_id
left join public.suppliers as s
  on s.id = pt.supplier_id
left join public.projects as p
  on p.id = pt.project_id;

create or replace view public.app_worker_transactions
with (security_invoker = true)
as
select
  pt.id,
  pt.worker_id,
  pt.project_id,
  p.name as project_name,
  pt.type,
  pt.amount,
  pt.currency,
  pt.description,
  pt.date,
  pt.created_at,
  pt.amount_usd,
  pt.amount_iqd,
  pt.source_invoice_id,
  pt.source_kind
from public.party_transactions as pt
left join public.projects as p
  on p.id = pt.project_id
where pt.party_type = 'worker';

create or replace view public.app_supplier_transactions
with (security_invoker = true)
as
select
  pt.id,
  pt.supplier_id,
  pt.project_id,
  p.name as project_name,
  pt.type,
  pt.amount,
  pt.currency,
  pt.description,
  pt.date,
  pt.created_at,
  pt.amount_usd,
  pt.amount_iqd,
  pt.source_invoice_id,
  pt.source_kind
from public.party_transactions as pt
left join public.projects as p
  on p.id = pt.project_id
where pt.party_type = 'supplier';

create or replace function public.recalculate_worker_balance(target_worker_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_worker_id is null then
    return;
  end if;

  update public.workers
  set
    balance = coalesce(
      (
        select sum(case when pt.type = 'credit' then pt.amount else -pt.amount end)
        from public.party_transactions as pt
        where pt.party_type = 'worker'
          and pt.worker_id = target_worker_id
      ),
      0
    ),
    balance_usd = coalesce(
      (
        select sum(case when pt.type = 'credit' then pt.amount_usd else -pt.amount_usd end)
        from public.party_transactions as pt
        where pt.party_type = 'worker'
          and pt.worker_id = target_worker_id
      ),
      0
    ),
    balance_iqd = coalesce(
      (
        select sum(case when pt.type = 'credit' then pt.amount_iqd else -pt.amount_iqd end)
        from public.party_transactions as pt
        where pt.party_type = 'worker'
          and pt.worker_id = target_worker_id
      ),
      0
    )
  where id = target_worker_id;
end;
$$;

create or replace function public.sync_worker_balance_from_party_transactions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op in ('UPDATE', 'DELETE') and old.worker_id is not null then
    perform public.recalculate_worker_balance(old.worker_id);
  end if;

  if tg_op in ('INSERT', 'UPDATE') and new.worker_id is not null then
    perform public.recalculate_worker_balance(new.worker_id);
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_sync_worker_balance_from_party_transactions on public.party_transactions;
create trigger trg_sync_worker_balance_from_party_transactions
after insert or update or delete on public.party_transactions
for each row execute function public.sync_worker_balance_from_party_transactions();

create or replace function public.sync_expense_party_transactions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  credit_amount numeric;
  credit_currency text;
  debit_amount numeric;
  debit_currency text;
  source_date date;
  source_kind text;
  source_title text;
  target_supplier_id bigint;
  target_worker_id bigint;
begin
  if tg_op in ('UPDATE', 'DELETE') then
    delete from public.party_transactions
    where source_invoice_id = old.id
      and source_kind in ('labor_expense', 'supplier_expense');
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  if new.record_status <> 'active' then
    return new;
  end if;

  if new.expense_type = 'labor' and new.labor_worker_id is not null then
    target_worker_id := new.labor_worker_id;
    source_kind := 'labor_expense';
  elsif new.expense_type = 'products' and new.supplier_id is not null then
    target_supplier_id := new.supplier_id;
    source_kind := 'supplier_expense';
  else
    return new;
  end if;

  source_title := coalesce(nullif(new.number, ''), 'Expense');
  source_date := coalesce(new.invoice_date, current_date);
  credit_amount := case
    when coalesce(new.total_amount_usd, 0) > 0 then coalesce(new.total_amount_usd, 0)
    else coalesce(new.total_amount_iqd, 0)
  end;
  credit_currency := case
    when coalesce(new.total_amount_usd, 0) > 0 then 'USD'
    else 'IQD'
  end;
  debit_amount := case
    when coalesce(new.paid_amount_usd, 0) > 0 then coalesce(new.paid_amount_usd, 0)
    else coalesce(new.paid_amount_iqd, 0)
  end;
  debit_currency := case
    when coalesce(new.paid_amount_usd, 0) > 0 then 'USD'
    else 'IQD'
  end;

  if coalesce(new.total_amount_usd, 0) > 0 or coalesce(new.total_amount_iqd, 0) > 0 then
    insert into public.party_transactions (
      party_type,
      worker_id,
      supplier_id,
      project_id,
      type,
      amount,
      currency,
      amount_usd,
      amount_iqd,
      description,
      date,
      source_invoice_id,
      source_kind
    )
    values (
      case when target_worker_id is not null then 'worker' else 'supplier' end,
      target_worker_id,
      target_supplier_id,
      new.project_id,
      'credit',
      credit_amount,
      credit_currency,
      coalesce(new.total_amount_usd, 0),
      coalesce(new.total_amount_iqd, 0),
      case
        when source_kind = 'labor_expense' then 'Labor earned: ' || source_title
        else 'Supplier invoice: ' || source_title
      end,
      source_date,
      new.id,
      source_kind
    );
  end if;

  if coalesce(new.paid_amount_usd, 0) > 0 or coalesce(new.paid_amount_iqd, 0) > 0 then
    insert into public.party_transactions (
      party_type,
      worker_id,
      supplier_id,
      project_id,
      type,
      amount,
      currency,
      amount_usd,
      amount_iqd,
      description,
      date,
      source_invoice_id,
      source_kind
    )
    values (
      case when target_worker_id is not null then 'worker' else 'supplier' end,
      target_worker_id,
      target_supplier_id,
      new.project_id,
      'debit',
      debit_amount,
      debit_currency,
      coalesce(new.paid_amount_usd, 0),
      coalesce(new.paid_amount_iqd, 0),
      case
        when source_kind = 'labor_expense' then 'Labor paid: ' || source_title
        else 'Supplier paid: ' || source_title
      end,
      source_date,
      new.id,
      source_kind
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_sync_expense_party_transactions on public.invoices;
create trigger trg_sync_expense_party_transactions
after insert or update or delete on public.invoices
for each row execute function public.sync_expense_party_transactions();

update public.workers as w
set
  balance = coalesce(
    (
      select sum(case when pt.type = 'credit' then pt.amount else -pt.amount end)
      from public.party_transactions as pt
      where pt.party_type = 'worker'
        and pt.worker_id = w.id
    ),
    0
  ),
  balance_usd = coalesce(
    (
      select sum(case when pt.type = 'credit' then pt.amount_usd else -pt.amount_usd end)
      from public.party_transactions as pt
      where pt.party_type = 'worker'
        and pt.worker_id = w.id
    ),
    0
  ),
  balance_iqd = coalesce(
    (
      select sum(case when pt.type = 'credit' then pt.amount_iqd else -pt.amount_iqd end)
      from public.party_transactions as pt
      where pt.party_type = 'worker'
        and pt.worker_id = w.id
    ),
    0
  );

create or replace function public.get_dashboard_overview()
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
with visible_projects as (
  select id, name, status
  from public.projects
),
visible_invoices as (
  select
    id,
    number,
    status,
    supplier_name,
    project_name,
    project_id,
    total_amount,
    paid_amount,
    remaining_amount,
    total_amount_usd,
    paid_amount_usd,
    remaining_amount_usd,
    total_amount_iqd,
    paid_amount_iqd,
    remaining_amount_iqd
  from public.app_invoices
  where record_status = 'active'
),
visible_workers as (
  select id, name, role, balance, balance_usd, balance_iqd
  from public.workers
),
visible_transactions as (
  select worker_id, type, amount, amount_usd, amount_iqd
  from public.app_worker_transactions
),
project_summaries as (
  select
    p.id,
    p.name,
    p.status,
    count(i.id)::int as invoice_count,
    coalesce(sum(i.total_amount), 0)::numeric(12,2) as total_invoiced,
    coalesce(sum(i.paid_amount), 0)::numeric(12,2) as total_paid,
    coalesce(sum(i.remaining_amount), 0)::numeric(12,2) as remaining,
    coalesce(sum(i.total_amount_usd), 0)::numeric(12,2) as total_invoiced_usd,
    coalesce(sum(i.paid_amount_usd), 0)::numeric(12,2) as total_paid_usd,
    coalesce(sum(i.remaining_amount_usd), 0)::numeric(12,2) as remaining_usd,
    coalesce(sum(i.total_amount_iqd), 0)::numeric(12,2) as total_invoiced_iqd,
    coalesce(sum(i.paid_amount_iqd), 0)::numeric(12,2) as total_paid_iqd,
    coalesce(sum(i.remaining_amount_iqd), 0)::numeric(12,2) as remaining_iqd
  from visible_projects as p
  left join visible_invoices as i
    on i.project_id = p.id
  group by p.id, p.name, p.status
),
worker_summaries as (
  select
    w.id,
    w.name,
    w.role,
    w.balance,
    w.balance_usd,
    w.balance_iqd,
    coalesce(sum(case when wt.type = 'credit' then wt.amount else 0 end), 0)::numeric(12,2) as total_credit,
    coalesce(sum(case when wt.type = 'debit' then wt.amount else 0 end), 0)::numeric(12,2) as total_debit,
    coalesce(sum(case when wt.type = 'credit' then wt.amount_usd else 0 end), 0)::numeric(12,2) as total_credit_usd,
    coalesce(sum(case when wt.type = 'debit' then wt.amount_usd else 0 end), 0)::numeric(12,2) as total_debit_usd,
    coalesce(sum(case when wt.type = 'credit' then wt.amount_iqd else 0 end), 0)::numeric(12,2) as total_credit_iqd,
    coalesce(sum(case when wt.type = 'debit' then wt.amount_iqd else 0 end), 0)::numeric(12,2) as total_debit_iqd
  from visible_workers as w
  left join visible_transactions as wt
    on wt.worker_id = w.id
  group by w.id, w.name, w.role, w.balance, w.balance_usd, w.balance_iqd
),
invoice_summaries as (
  select
    id,
    number,
    status,
    supplier_name,
    project_name,
    total_amount,
    paid_amount,
    remaining_amount as remaining,
    total_amount_usd,
    paid_amount_usd,
    remaining_amount_usd as remaining_usd,
    total_amount_iqd,
    paid_amount_iqd,
    remaining_amount_iqd as remaining_iqd
  from visible_invoices
)
select jsonb_build_object(
  'totalWorkers',
  (select count(*) from visible_workers),
  'activeProjects',
  (select count(*) from visible_projects where status = 'active'),
  'totalSuppliers',
  (select count(*) from public.suppliers),
  'invoicesUnpaid',
  (select count(*) from visible_invoices where status <> 'paid'),
  'totalInvoiceAmount',
  coalesce((select sum(total_amount) from visible_invoices), 0),
  'totalPaidAmount',
  coalesce((select sum(paid_amount) from visible_invoices), 0),
  'remainingAmount',
  coalesce((select sum(remaining_amount) from visible_invoices), 0),
  'totalInvoiceAmountUsd',
  coalesce((select sum(total_amount_usd) from visible_invoices), 0),
  'totalPaidAmountUsd',
  coalesce((select sum(paid_amount_usd) from visible_invoices), 0),
  'remainingAmountUsd',
  coalesce((select sum(remaining_amount_usd) from visible_invoices), 0),
  'totalInvoiceAmountIqd',
  coalesce((select sum(total_amount_iqd) from visible_invoices), 0),
  'totalPaidAmountIqd',
  coalesce((select sum(paid_amount_iqd) from visible_invoices), 0),
  'remainingAmountIqd',
  coalesce((select sum(remaining_amount_iqd) from visible_invoices), 0),
  'projectsSummary',
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', ps.id,
          'name', ps.name,
          'status', ps.status,
          'invoiceCount', ps.invoice_count,
          'totalInvoiced', ps.total_invoiced,
          'totalPaid', ps.total_paid,
          'remaining', ps.remaining,
          'totalInvoicedUsd', ps.total_invoiced_usd,
          'totalPaidUsd', ps.total_paid_usd,
          'remainingUsd', ps.remaining_usd,
          'totalInvoicedIqd', ps.total_invoiced_iqd,
          'totalPaidIqd', ps.total_paid_iqd,
          'remainingIqd', ps.remaining_iqd
        )
        order by ps.remaining_usd desc, ps.remaining_iqd desc, ps.name asc
      )
      from project_summaries as ps
    ),
    '[]'::jsonb
  ),
  'workersSummary',
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', ws.id,
          'name', ws.name,
          'role', ws.role,
          'balance', ws.balance,
          'balanceUsd', ws.balance_usd,
          'balanceIqd', ws.balance_iqd,
          'totalCredit', ws.total_credit,
          'totalDebit', ws.total_debit,
          'totalCreditUsd', ws.total_credit_usd,
          'totalDebitUsd', ws.total_debit_usd,
          'totalCreditIqd', ws.total_credit_iqd,
          'totalDebitIqd', ws.total_debit_iqd
        )
        order by abs(ws.balance_usd) desc, abs(ws.balance_iqd) desc, ws.name asc
      )
      from worker_summaries as ws
    ),
    '[]'::jsonb
  ),
  'invoicesSummary',
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', inv.id,
          'number', inv.number,
          'status', inv.status,
          'supplierName', inv.supplier_name,
          'projectName', inv.project_name,
          'totalAmount', inv.total_amount,
          'paidAmount', inv.paid_amount,
          'remaining', inv.remaining,
          'totalAmountUsd', inv.total_amount_usd,
          'paidAmountUsd', inv.paid_amount_usd,
          'remainingUsd', inv.remaining_usd,
          'totalAmountIqd', inv.total_amount_iqd,
          'paidAmountIqd', inv.paid_amount_iqd,
          'remainingIqd', inv.remaining_iqd
        )
        order by inv.remaining_usd desc, inv.remaining_iqd desc, inv.number asc
      )
      from invoice_summaries as inv
    ),
    '[]'::jsonb
  )
);
$$;

grant select on public.app_party_transactions to authenticated;
grant select on public.app_worker_transactions to authenticated;
grant select on public.app_supplier_transactions to authenticated;
grant execute on function public.recalculate_worker_balance(bigint) to authenticated;
