-- Migration corrective : Restaurer les vues supprimées par erreur
-- La migration 202604270000_cleanup_and_optimize.sql a supprimé des vues encore utilisées par l'application

-- =====================================================
-- 1. RESTAURER LA TABLE income_transaction_history
-- =====================================================

CREATE TABLE IF NOT EXISTS public.income_transaction_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  income_transaction_id bigint NOT NULL REFERENCES public.income_transactions(id) ON DELETE CASCADE,
  change_type text NOT NULL CHECK (change_type IN ('created', 'updated', 'deleted')),
  project_id bigint REFERENCES public.projects(id) ON DELETE SET NULL,
  project_name text,
  amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (amount > 0),
  currency text NOT NULL DEFAULT 'USD' CHECK (currency IN ('USD', 'IQD')),
  description text,
  date date,
  record_status text NOT NULL DEFAULT 'active' CHECK (record_status IN ('active', 'deleted')),
  changed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  changed_by_name text,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_income_transaction_history_income_id
  ON public.income_transaction_history(income_transaction_id);

CREATE INDEX IF NOT EXISTS idx_income_transaction_history_changed_at
  ON public.income_transaction_history(changed_at);

-- =====================================================
-- 2. RESTAURER LE TRIGGER D'HISTORIQUE DES REVENUS
-- =====================================================

CREATE OR REPLACE FUNCTION public.log_income_transaction_history()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  actor_id uuid;
  actor_name text;
  snapshot_project_name text;
  snapshot_change_type text;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW IS NOT DISTINCT FROM OLD THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    actor_id := COALESCE(auth.uid(), NEW.created_by);
    snapshot_change_type := 'created';
  ELSE
    actor_id := COALESCE(auth.uid(), NEW.deleted_by, NEW.created_by, OLD.created_by);
    snapshot_change_type := CASE
      WHEN NEW.record_status = 'deleted' AND OLD.record_status IS DISTINCT FROM NEW.record_status THEN 'deleted'
      ELSE 'updated'
    END;
  END IF;

  IF actor_id IS NOT NULL THEN
    SELECT COALESCE(p.full_name, p.email)
    INTO actor_name
    FROM public.profiles AS p
    WHERE p.id = actor_id;
  END IF;

  IF NEW.project_id IS NOT NULL THEN
    SELECT p.name
    INTO snapshot_project_name
    FROM public.projects AS p
    WHERE p.id = NEW.project_id;
  END IF;

  INSERT INTO public.income_transaction_history (
    income_transaction_id,
    change_type,
    project_id,
    project_name,
    amount,
    currency,
    description,
    date,
    record_status,
    changed_by,
    changed_by_name,
    changed_at
  )
  VALUES (
    NEW.id,
    snapshot_change_type,
    NEW.project_id,
    snapshot_project_name,
    NEW.amount,
    NEW.currency,
    NEW.description,
    NEW.date,
    NEW.record_status,
    actor_id,
    actor_name,
    CASE WHEN TG_OP = 'INSERT' THEN COALESCE(NEW.created_at, now()) ELSE now() END
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_income_transaction_history ON public.income_transactions;
CREATE TRIGGER trg_log_income_transaction_history
AFTER INSERT OR UPDATE ON public.income_transactions
FOR EACH ROW EXECUTE FUNCTION public.log_income_transaction_history();

-- =====================================================
-- 3. RESTAURER LA VUE app_income_transaction_history
-- =====================================================

DROP VIEW IF EXISTS public.app_income_transaction_history;

CREATE OR REPLACE VIEW public.app_income_transaction_history
WITH (security_invoker = true)
AS
SELECT
  ith.id,
  ith.income_transaction_id,
  ith.change_type,
  ith.project_id,
  ith.project_name,
  ith.amount,
  ith.currency,
  ith.description,
  ith.date,
  ith.record_status,
  ith.changed_by,
  ith.changed_by_name,
  ith.changed_at
FROM public.income_transaction_history AS ith;

-- =====================================================
-- 4. RESTAURER LA VUE app_party_transactions
-- =====================================================

DROP VIEW IF EXISTS public.app_party_transactions;

CREATE OR REPLACE VIEW public.app_party_transactions
WITH (security_invoker = true)
AS
SELECT
  pt.id,
  pt.party_type,
  COALESCE(pt.worker_id, pt.supplier_id) AS party_id,
  COALESCE(w.name, s.name) AS party_name,
  pt.worker_id,
  w.name AS worker_name,
  pt.supplier_id,
  s.name AS supplier_name,
  pt.project_id,
  p.name AS project_name,
  pt.type,
  pt.amount,
  pt.currency,
  pt.description,
  pt.date,
  pt.created_at,
  pt.amount_usd,
  pt.amount_iqd,
  pt.source_invoice_id,
  pt.source_kind,
  pt.expense_category,
  pt.created_by,
  COALESCE(created_profile.full_name, created_profile.email) AS created_by_name
FROM public.party_transactions AS pt
LEFT JOIN public.workers AS w ON w.id = pt.worker_id
LEFT JOIN public.suppliers AS s ON s.id = pt.supplier_id
LEFT JOIN public.projects AS p ON p.id = pt.project_id
LEFT JOIN public.profiles AS created_profile ON created_profile.id = pt.created_by;

-- =====================================================
-- 5. RESTAURER LA VUE app_worker_transactions
-- =====================================================

DROP VIEW IF EXISTS public.app_worker_transactions;

CREATE OR REPLACE VIEW public.app_worker_transactions
WITH (security_invoker = true)
AS
SELECT
  pt.id,
  pt.worker_id,
  pt.project_id,
  p.name AS project_name,
  pt.type,
  pt.amount,
  pt.currency,
  pt.description,
  pt.date,
  pt.created_at,
  pt.amount_usd,
  pt.amount_iqd,
  pt.source_invoice_id,
  pt.source_kind,
  pt.expense_category,
  pt.created_by,
  COALESCE(created_profile.full_name, created_profile.email) AS created_by_name
FROM public.party_transactions AS pt
LEFT JOIN public.projects AS p ON p.id = pt.project_id
LEFT JOIN public.profiles AS created_profile ON created_profile.id = pt.created_by
WHERE pt.party_type = 'worker';

-- =====================================================
-- 6. RESTAURER LA VUE app_supplier_transactions
-- =====================================================

DROP VIEW IF EXISTS public.app_supplier_transactions;

CREATE OR REPLACE VIEW public.app_supplier_transactions
WITH (security_invoker = true)
AS
SELECT
  pt.id,
  pt.supplier_id,
  pt.project_id,
  p.name AS project_name,
  pt.type,
  pt.amount,
  pt.currency,
  pt.description,
  pt.date,
  pt.created_at,
  pt.amount_usd,
  pt.amount_iqd,
  pt.source_invoice_id,
  pt.source_kind,
  pt.expense_category,
  pt.created_by,
  COALESCE(created_profile.full_name, created_profile.email) AS created_by_name
FROM public.party_transactions AS pt
LEFT JOIN public.projects AS p ON p.id = pt.project_id
LEFT JOIN public.profiles AS created_profile ON created_profile.id = pt.created_by
WHERE pt.party_type = 'supplier';

-- =====================================================
-- 7. RESTAURER LA TABLE ET VUE invoice_history
-- =====================================================

CREATE TABLE IF NOT EXISTS public.invoice_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  change_type text NOT NULL CHECK (change_type IN ('created', 'updated')),
  number text NOT NULL,
  supplier_id bigint REFERENCES public.suppliers(id) ON DELETE SET NULL,
  supplier_name text,
  project_id bigint REFERENCES public.projects(id) ON DELETE SET NULL,
  project_name text,
  building_id bigint REFERENCES public.project_buildings(id) ON DELETE SET NULL,
  building_name text,
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL,
  product_name text,
  total_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  paid_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0 AND paid_amount <= total_amount),
  currency text NOT NULL DEFAULT 'USD' CHECK (currency IN ('USD', 'IQD')),
  status text NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'partial', 'paid')),
  invoice_date date,
  due_date date,
  notes text,
  image_url text,
  changed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  changed_by_name text,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_invoice_history_invoice_id ON public.invoice_history(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_history_changed_at ON public.invoice_history(changed_at);

-- Trigger pour invoice_history
CREATE OR REPLACE FUNCTION public.log_invoice_history()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  actor_id uuid;
  actor_name text;
  snapshot_supplier_name text;
  snapshot_project_name text;
  snapshot_building_name text;
  snapshot_product_name text;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW IS NOT DISTINCT FROM OLD THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    actor_id := COALESCE(auth.uid(), NEW.created_by);
  ELSE
    actor_id := COALESCE(auth.uid(), NEW.created_by, OLD.created_by);
  END IF;

  IF actor_id IS NOT NULL THEN
    SELECT COALESCE(p.full_name, p.email)
    INTO actor_name
    FROM public.profiles AS p
    WHERE p.id = actor_id;
  END IF;

  IF NEW.supplier_id IS NOT NULL THEN
    SELECT s.name
    INTO snapshot_supplier_name
    FROM public.suppliers AS s
    WHERE s.id = NEW.supplier_id;
  END IF;

  IF NEW.project_id IS NOT NULL THEN
    SELECT p.name
    INTO snapshot_project_name
    FROM public.projects AS p
    WHERE p.id = NEW.project_id;
  END IF;

  IF NEW.building_id IS NOT NULL THEN
    SELECT pb.name
    INTO snapshot_building_name
    FROM public.project_buildings AS pb
    WHERE pb.id = NEW.building_id;
  END IF;

  IF NEW.product_id IS NOT NULL THEN
    SELECT pr.name
    INTO snapshot_product_name
    FROM public.products AS pr
    WHERE pr.id = NEW.product_id;
  END IF;

  INSERT INTO public.invoice_history (
    invoice_id,
    change_type,
    number,
    supplier_id,
    supplier_name,
    project_id,
    project_name,
    building_id,
    building_name,
    product_id,
    product_name,
    total_amount,
    paid_amount,
    currency,
    status,
    invoice_date,
    due_date,
    notes,
    image_url,
    changed_by,
    changed_by_name,
    changed_at
  )
  VALUES (
    NEW.id,
    CASE WHEN TG_OP = 'INSERT' THEN 'created' ELSE 'updated' END,
    NEW.number,
    NEW.supplier_id,
    snapshot_supplier_name,
    NEW.project_id,
    snapshot_project_name,
    NEW.building_id,
    snapshot_building_name,
    NEW.product_id,
    snapshot_product_name,
    NEW.total_amount,
    NEW.paid_amount,
    NEW.currency,
    NEW.status,
    NEW.invoice_date,
    NEW.due_date,
    NEW.notes,
    NEW.image_url,
    actor_id,
    actor_name,
    CASE WHEN TG_OP = 'INSERT' THEN COALESCE(NEW.created_at, now()) ELSE now() END
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_log_invoice_history ON public.invoices;
CREATE TRIGGER trg_log_invoice_history
AFTER INSERT OR UPDATE ON public.invoices
FOR EACH ROW EXECUTE FUNCTION public.log_invoice_history();

-- Vue app_invoice_history
DROP VIEW IF EXISTS public.app_invoice_history;

CREATE OR REPLACE VIEW public.app_invoice_history
WITH (security_invoker = true)
AS
SELECT
  ih.id,
  ih.invoice_id,
  ih.change_type,
  ih.number,
  ih.status,
  ih.supplier_id,
  ih.supplier_name,
  ih.project_id,
  ih.project_name,
  ih.building_id,
  ih.building_name,
  ih.product_id,
  ih.product_name,
  ih.total_amount,
  ih.paid_amount,
  GREATEST(ih.total_amount - ih.paid_amount, 0) AS remaining_amount,
  ih.currency,
  ih.invoice_date,
  ih.due_date,
  ih.notes,
  ih.image_url,
  ih.changed_by,
  ih.changed_by_name,
  ih.changed_at
FROM public.invoice_history AS ih;

ALTER TABLE public.invoice_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "invoice history scoped read" ON public.invoice_history;
CREATE POLICY "invoice history scoped read"
ON public.invoice_history
FOR SELECT
TO authenticated
USING (public.can_access_project(project_id));

-- =====================================================
-- 8. POLITIQUES RLS POUR income_transaction_history
-- =====================================================

ALTER TABLE public.income_transaction_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "income transaction history scoped read" ON public.income_transaction_history;
CREATE POLICY "income transaction history scoped read"
ON public.income_transaction_history
FOR SELECT
TO authenticated
USING (public.can_access_project(project_id));

-- =====================================================
-- 9. GRANT PERMISSIONS
-- =====================================================

GRANT SELECT ON public.app_income_transaction_history TO authenticated;
GRANT SELECT ON public.app_party_transactions TO authenticated;
GRANT SELECT ON public.app_worker_transactions TO authenticated;
GRANT SELECT ON public.app_supplier_transactions TO authenticated;
GRANT SELECT ON public.app_invoice_history TO authenticated;

-- =====================================================
-- 10. COMMENTAIRES
-- =====================================================

COMMENT ON VIEW public.app_party_transactions IS 'Unified view of party transactions with worker/supplier names and project info';
COMMENT ON VIEW public.app_worker_transactions IS 'View of worker transactions with project names';
COMMENT ON VIEW public.app_supplier_transactions IS 'View of supplier transactions with project names';
COMMENT ON VIEW public.app_income_transaction_history IS 'History view of income transaction changes';
COMMENT ON VIEW public.app_invoice_history IS 'History view of invoice changes';
