create table if not exists public.specialities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.worker_specialities (
  worker_id bigint not null references public.workers(id) on delete cascade,
  speciality_id bigint not null references public.specialities(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (worker_id, speciality_id)
);

alter table public.specialities enable row level security;
alter table public.worker_specialities enable row level security;

drop policy if exists "Allow read access for all users" on public.specialities;
create policy "Allow read access for all users" on public.specialities
  for select using (true);

drop policy if exists "Allow read access for all users" on public.worker_specialities;
create policy "Allow read access for all users" on public.worker_specialities
  for select using (true);

drop policy if exists "Allow insert for authenticated users" on public.worker_specialities;
create policy "Allow insert for authenticated users" on public.worker_specialities
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Allow update for authenticated users" on public.worker_specialities;
create policy "Allow update for authenticated users" on public.worker_specialities
  for update using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Allow delete for authenticated users" on public.worker_specialities;
create policy "Allow delete for authenticated users" on public.worker_specialities
  for delete using (auth.role() = 'authenticated');
