create table if not exists public.income_transaction_history (
  id bigint generated by default as identity primary key,
  income_transaction_id bigint not null references public.income_transactions(id) on delete cascade,
  change_type text not null check (change_type in ('created', 'updated', 'deleted')),
  project_id bigint references public.projects(id) on delete set null,
  project_name text,
  amount numeric(12,2) not null default 0 check (amount > 0),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  description text,
  date date,
  record_status text not null default 'active' check (record_status in ('active', 'deleted')),
  changed_by uuid references public.profiles(id) on delete set null,
  changed_by_name text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_income_transaction_history_income_id
  on public.income_transaction_history(income_transaction_id);

create index if not exists idx_income_transaction_history_changed_at
  on public.income_transaction_history(changed_at);

create or replace function public.log_income_transaction_history()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  actor_id uuid;
  actor_name text;
  snapshot_project_name text;
  snapshot_change_type text;
begin
  if tg_op = 'UPDATE' and new is not distinct from old then
    return new;
  end if;

  if tg_op = 'INSERT' then
    actor_id := coalesce(auth.uid(), new.created_by);
    snapshot_change_type := 'created';
  else
    actor_id := coalesce(auth.uid(), new.deleted_by, new.created_by, old.created_by);
    snapshot_change_type := case
      when new.record_status = 'deleted' and old.record_status is distinct from new.record_status then 'deleted'
      else 'updated'
    end;
  end if;

  if actor_id is not null then
    select coalesce(p.full_name, p.email)
    into actor_name
    from public.profiles as p
    where p.id = actor_id;
  end if;

  if new.project_id is not null then
    select p.name
    into snapshot_project_name
    from public.projects as p
    where p.id = new.project_id;
  end if;

  insert into public.income_transaction_history (
    income_transaction_id,
    change_type,
    project_id,
    project_name,
    amount,
    currency,
    description,
    date,
    record_status,
    changed_by,
    changed_by_name,
    changed_at
  )
  values (
    new.id,
    snapshot_change_type,
    new.project_id,
    snapshot_project_name,
    new.amount,
    new.currency,
    new.description,
    new.date,
    new.record_status,
    actor_id,
    actor_name,
    case when tg_op = 'INSERT' then coalesce(new.created_at, now()) else now() end
  );

  return new;
end;
$$;

drop trigger if exists trg_log_income_transaction_history on public.income_transactions;
create trigger trg_log_income_transaction_history
after insert or update on public.income_transactions
for each row execute function public.log_income_transaction_history();

insert into public.income_transaction_history (
  income_transaction_id,
  change_type,
  project_id,
  project_name,
  amount,
  currency,
  description,
  date,
  record_status,
  changed_by,
  changed_by_name,
  changed_at
)
select
  it.id,
  case when it.record_status = 'deleted' then 'deleted' else 'created' end,
  it.project_id,
  p.name,
  it.amount,
  it.currency,
  it.description,
  it.date,
  it.record_status,
  it.created_by,
  coalesce(created_profile.full_name, created_profile.email),
  coalesce(it.created_at, now())
from public.income_transactions as it
left join public.projects as p
  on p.id = it.project_id
left join public.profiles as created_profile
  on created_profile.id = it.created_by
where not exists (
  select 1
  from public.income_transaction_history as ith
  where ith.income_transaction_id = it.id
);

create or replace view public.app_income_transaction_history
with (security_invoker = true)
as
select
  ith.id,
  ith.income_transaction_id,
  ith.change_type,
  ith.project_id,
  ith.project_name,
  ith.amount,
  ith.currency,
  ith.description,
  ith.date,
  ith.record_status,
  ith.changed_by,
  ith.changed_by_name,
  ith.changed_at
from public.income_transaction_history as ith;

alter table public.income_transaction_history enable row level security;

drop policy if exists "income transaction history scoped read" on public.income_transaction_history;
create policy "income transaction history scoped read"
on public.income_transaction_history
for select
to authenticated
using (public.can_access_project(project_id));

drop policy if exists "income transaction history authenticated insert" on public.income_transaction_history;
create policy "income transaction history authenticated insert"
on public.income_transaction_history
for insert
to authenticated
with check (public.can_access_project(project_id));

grant select on public.app_income_transaction_history to authenticated;
