insert into storage.buckets (id, name, public)
values ('project-files', 'project-files', false)
on conflict (id) do update
set public = false;

create table if not exists public.project_files (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  storage_path text not null unique,
  file_name text not null,
  mime_type text,
  file_size bigint not null default 0,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint project_files_file_size_check check (file_size >= 0),
  constraint project_files_storage_path_check check (storage_path like 'project-%/user-%/%')
);

create index if not exists idx_project_files_project_id_created_at
on public.project_files (project_id, created_at desc);

create index if not exists idx_project_files_uploaded_by
on public.project_files (uploaded_by);

create or replace function public.can_access_project_file_object(object_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  object_prefix text;
  project_id_text text;
begin
  if auth.role() <> 'authenticated' then
    return false;
  end if;

  object_prefix := split_part(coalesce(object_name, ''), '/', 1);

  if object_prefix not like 'project-%' then
    return false;
  end if;

  project_id_text := nullif(replace(object_prefix, 'project-', ''), '');
  if project_id_text is null or project_id_text !~ '^[0-9]+$' then
    return false;
  end if;

  return public.can_access_project(project_id_text::bigint);
exception
  when others then
    return false;
end;
$$;

create or replace function public.can_manage_project_file_object(object_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  uploader_prefix text;
  uploader_id_text text;
begin
  if not public.can_access_project_file_object(object_name) then
    return false;
  end if;

  if public.is_admin() then
    return true;
  end if;

  uploader_prefix := split_part(coalesce(object_name, ''), '/', 2);
  if uploader_prefix not like 'user-%' then
    return false;
  end if;

  uploader_id_text := nullif(replace(uploader_prefix, 'user-', ''), '');
  return uploader_id_text = auth.uid()::text;
exception
  when others then
    return false;
end;
$$;

alter table public.project_files enable row level security;

drop policy if exists "project files readable by membership" on public.project_files;
create policy "project files readable by membership"
on public.project_files
for select
to authenticated
using (public.can_access_project(project_id));

drop policy if exists "project files uploader insert" on public.project_files;
create policy "project files uploader insert"
on public.project_files
for insert
to authenticated
with check (
  uploaded_by = auth.uid()
  and public.can_access_project(project_id)
  and public.can_manage_project_file_object(storage_path)
);

drop policy if exists "project files owner or admin delete" on public.project_files;
create policy "project files owner or admin delete"
on public.project_files
for delete
to authenticated
using (
  public.can_access_project(project_id)
  and (public.is_admin() or uploaded_by = auth.uid())
);

drop policy if exists "project files storage read" on storage.objects;
create policy "project files storage read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'project-files'
  and public.can_access_project_file_object(name)
);

drop policy if exists "project files storage insert" on storage.objects;
create policy "project files storage insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'project-files'
  and public.can_manage_project_file_object(name)
);

drop policy if exists "project files storage update" on storage.objects;
create policy "project files storage update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'project-files'
  and public.can_manage_project_file_object(name)
)
with check (
  bucket_id = 'project-files'
  and public.can_manage_project_file_object(name)
);

drop policy if exists "project files storage delete" on storage.objects;
create policy "project files storage delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'project-files'
  and public.can_manage_project_file_object(name)
);

grant usage on schema public to authenticated;
grant select, insert, delete on public.project_files to authenticated;
grant usage, select on sequence public.project_files_id_seq to authenticated;
grant execute on function public.can_access_project_file_object(text) to authenticated;
grant execute on function public.can_manage_project_file_object(text) to authenticated;
