create table if not exists public.project_alerts (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  alert_date date not null,
  note text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint project_alerts_note_check check (length(btrim(note)) > 0)
);

create index if not exists idx_project_alerts_project_date
on public.project_alerts (project_id, alert_date asc, created_at desc);

create index if not exists idx_project_alerts_created_by
on public.project_alerts (created_by);

alter table public.project_alerts enable row level security;

drop policy if exists "project alerts readable by membership" on public.project_alerts;
create policy "project alerts readable by membership"
on public.project_alerts
for select
to authenticated
using (public.can_access_project(project_id));

drop policy if exists "project alerts member insert" on public.project_alerts;
create policy "project alerts member insert"
on public.project_alerts
for insert
to authenticated
with check (
  created_by = auth.uid()
  and public.can_access_project(project_id)
);

drop policy if exists "project alerts owner or admin delete" on public.project_alerts;
create policy "project alerts owner or admin delete"
on public.project_alerts
for delete
to authenticated
using (
  public.can_access_project(project_id)
  and (public.is_admin() or created_by = auth.uid())
);

grant usage on schema public to authenticated;
grant select, insert, delete on public.project_alerts to authenticated;
grant usage, select on sequence public.project_alerts_id_seq to authenticated;
