create table if not exists public.invoice_history (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  change_type text not null check (change_type in ('created', 'updated')),
  number text not null,
  supplier_id bigint references public.suppliers(id) on delete set null,
  supplier_name text,
  project_id bigint references public.projects(id) on delete set null,
  project_name text,
  building_id bigint references public.project_buildings(id) on delete set null,
  building_name text,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  paid_amount numeric(12,2) not null default 0 check (paid_amount >= 0 and paid_amount <= total_amount),
  currency text not null default 'USD' check (currency in ('USD', 'IQD')),
  status text not null default 'unpaid' check (status in ('unpaid', 'partial', 'paid')),
  invoice_date date,
  due_date date,
  notes text,
  image_url text,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_by_name text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_invoice_history_invoice_id on public.invoice_history(invoice_id);
create index if not exists idx_invoice_history_changed_at on public.invoice_history(changed_at);

create or replace function public.log_invoice_history()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  actor_id uuid;
  actor_name text;
  snapshot_supplier_name text;
  snapshot_project_name text;
  snapshot_building_name text;
  snapshot_product_name text;
begin
  if tg_op = 'UPDATE' and new is not distinct from old then
    return new;
  end if;

  if tg_op = 'INSERT' then
    actor_id := coalesce(auth.uid(), new.created_by);
  else
    actor_id := coalesce(auth.uid(), new.created_by, old.created_by);
  end if;

  if actor_id is not null then
    select coalesce(p.full_name, p.email)
    into actor_name
    from public.profiles as p
    where p.id = actor_id;
  end if;

  if new.supplier_id is not null then
    select s.name
    into snapshot_supplier_name
    from public.suppliers as s
    where s.id = new.supplier_id;
  end if;

  if new.project_id is not null then
    select p.name
    into snapshot_project_name
    from public.projects as p
    where p.id = new.project_id;
  end if;

  if new.building_id is not null then
    select pb.name
    into snapshot_building_name
    from public.project_buildings as pb
    where pb.id = new.building_id;
  end if;

  if new.product_id is not null then
    select pr.name
    into snapshot_product_name
    from public.products as pr
    where pr.id = new.product_id;
  end if;

  insert into public.invoice_history (
    invoice_id,
    change_type,
    number,
    supplier_id,
    supplier_name,
    project_id,
    project_name,
    building_id,
    building_name,
    product_id,
    product_name,
    total_amount,
    paid_amount,
    currency,
    status,
    invoice_date,
    due_date,
    notes,
    image_url,
    changed_by,
    changed_by_name,
    changed_at
  )
  values (
    new.id,
    case when tg_op = 'INSERT' then 'created' else 'updated' end,
    new.number,
    new.supplier_id,
    snapshot_supplier_name,
    new.project_id,
    snapshot_project_name,
    new.building_id,
    snapshot_building_name,
    new.product_id,
    snapshot_product_name,
    new.total_amount,
    new.paid_amount,
    new.currency,
    new.status,
    new.invoice_date,
    new.due_date,
    new.notes,
    new.image_url,
    actor_id,
    actor_name,
    case when tg_op = 'INSERT' then coalesce(new.created_at, now()) else now() end
  );

  return new;
end;
$$;

drop trigger if exists trg_log_invoice_history on public.invoices;
create trigger trg_log_invoice_history
after insert or update on public.invoices
for each row execute function public.log_invoice_history();

insert into public.invoice_history (
  invoice_id,
  change_type,
  number,
  supplier_id,
  supplier_name,
  project_id,
  project_name,
  building_id,
  building_name,
  product_id,
  product_name,
  total_amount,
  paid_amount,
  currency,
  status,
  invoice_date,
  due_date,
  notes,
  image_url,
  changed_by,
  changed_by_name,
  changed_at
)
select
  i.id,
  'created',
  i.number,
  i.supplier_id,
  s.name,
  i.project_id,
  p.name,
  i.building_id,
  pb.name,
  i.product_id,
  pr.name,
  i.total_amount,
  i.paid_amount,
  i.currency,
  i.status,
  i.invoice_date,
  i.due_date,
  i.notes,
  i.image_url,
  i.created_by,
  coalesce(created_profile.full_name, created_profile.email),
  coalesce(i.created_at, now())
from public.invoices as i
left join public.suppliers as s
  on s.id = i.supplier_id
left join public.projects as p
  on p.id = i.project_id
left join public.project_buildings as pb
  on pb.id = i.building_id
left join public.products as pr
  on pr.id = i.product_id
left join public.profiles as created_profile
  on created_profile.id = i.created_by
where not exists (
  select 1
  from public.invoice_history as ih
  where ih.invoice_id = i.id
);

create or replace view public.app_invoice_history
with (security_invoker = true)
as
select
  ih.id,
  ih.invoice_id,
  ih.change_type,
  ih.number,
  ih.status,
  ih.supplier_id,
  ih.supplier_name,
  ih.project_id,
  ih.project_name,
  ih.building_id,
  ih.building_name,
  ih.product_id,
  ih.product_name,
  ih.total_amount,
  ih.paid_amount,
  greatest(ih.total_amount - ih.paid_amount, 0) as remaining_amount,
  ih.currency,
  ih.invoice_date,
  ih.due_date,
  ih.notes,
  ih.image_url,
  ih.changed_by,
  ih.changed_by_name,
  ih.changed_at
from public.invoice_history as ih;

alter table public.invoice_history enable row level security;

drop policy if exists "invoice history scoped read" on public.invoice_history;
create policy "invoice history scoped read"
on public.invoice_history
for select
to authenticated
using (public.can_access_project(project_id));

drop policy if exists "invoice history authenticated insert" on public.invoice_history;
create policy "invoice history authenticated insert"
on public.invoice_history
for insert
to authenticated
with check (public.can_access_project(project_id));

grant select on public.app_invoice_history to authenticated;
